# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MoviesVIPER' do
  use_frameworks!

	pod 'Alamofire'
    pod 'Gloss'

  target 'MoviesVIPERTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
