# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MoviesVIPER' do
  use_frameworks!

	pod 'Alamofire'

  target 'MoviesVIPERTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
